apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-stack-release

resources:
  - ../base
  - namespace.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production

commonLabels:
  environment: release