apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yaml
  - configmap-backend.yaml
  - configmap-frontend.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - frontend-nodeport.yaml
  - ingress.yaml

# Common labels for all resources
commonLabels:
  app: realworld
  version: v1

# Name prefix for all resources
namePrefix: realworld-

# Images to be updated during deployment
images:
  - name: realworld-example-app_backend
    newName: realworld-backend
  - name: realworld-example-app_frontend  
    newName: realworld-frontend