apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-stack
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "myappdb"
  NODE_ENV: "development"