apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap-backend.yaml
  - configmap-frontend.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - frontend-nodeport.yaml

commonLabels:
  app: realworld-app
  version: v1