apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-stack
type: Opaque
data:
  # echo -n "postgres" | base64
  database-user: cG9zdGdyZXM=
  # echo -n "mysecretpassword" | base64
  database-password: bXlzZWNyZXRwYXNzd29yZA==